fix: run controller process as non-root
In #1406, we set `runAsNonRoot: true` for the controller but the
Tilt controller Dockerfile makes the process try to run as root,
resulting in the following error in the controller pod:

Error: container has runAsNonRoot and image will run as root

Ensure Tilt runs the controller as non-root. Also make the controller
filesystem writeable for Tilt (since Tilt relies on live updates to a
running container).

Signed-off-by: Johanan Liebermann <jliebermann@microsoft.com>